[platformio]
env_default = esp12e

[env:esp12e]
platform = espressif8266
framework = arduino
board = nodemcuv2

monitor_speed = 115200
; upload_speed = 230400
; upload_speed = 460800

upload_protocol = espota
upload_port = co2-sensor.local

build_flags = -DMQTT_MAX_PACKET_SIZE=512

lib_deps =
    tobiasschuerg/MH-Z CO2 Sensors
    kitesurfer1404/WS2812FX
    bblanchon/ArduinoJson
    knolleary/PubSubClient
    snakeye/RecurringTask
